# Generated by Django 2.1.11 on 2019-09-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('Outcome1', 'Outcome 1'), ('Outcome2', 'Outcome 2'), ('Outcome3', 'Outcome 3'), ('Outcome4', 'Outcome 4')], default='outcome 1', max_length=8)),
                ('activity', models.CharField(max_length=500)),
                ('sub_activity', models.CharField(max_length=500)),
                ('cost', models.FloatField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
