# Generated by Django 2.1.11 on 2019-10-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('Outcome1', 'Outcome 1'), ('Outcome2', 'Outcome 2'), ('Outcome3', 'Outcome 3'), ('Outcome4', 'Outcome 4')], default='', max_length=8)),
                ('total_budget', models.FloatField(default='', help_text='Please enter the total budget for your outcome', max_length=100)),
                ('activity', models.CharField(help_text='Please Enter the activity you are reporting for', max_length=500)),
                ('sub_activity', models.CharField(help_text='Please Enter the sub_activity of the above activity', max_length=500)),
                ('cost', models.FloatField(help_text='Enter the cost of the gender activity', max_length=500)),
                ('description', models.TextField(help_text='Tell us more here', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CalculateTotals',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genderTrack.Activity')),
                ('select_outcome', models.ForeignKey(default='outcome 1', on_delete=django.db.models.deletion.PROTECT, related_name='tags', related_query_name='tag', to='genderTrack.Activity')),
            ],
            bases=('genderTrack.activity',),
        ),
    ]
