# Generated by Django 2.1.11 on 2019-09-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genderTrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_budget',
            field=models.FloatField(default='', help_text='Please enter the total budget for your outcome', max_length=100),
        ),
        migrations.AddField(
            model_name='calculatetotals',
            name='select_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genderTrack.Activity'),
        ),
    ]
