# Generated by Django 2.1.11 on 2019-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.FloatField(help_text='Enter the actual cost of the activity above', max_length=300),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(help_text='Enter a brief description of the activity', max_length=300),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sub_activity',
            field=models.CharField(help_text='Enter the sub activity if any', max_length=300),
        ),
        migrations.AlterField(
            model_name='outcomeinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('F', 'Full Target'), ('M', 'Medium Target'), ('B', 'Below Target')], default='m', help_text='Status of the target', max_length=1),
        ),
    ]
