# Generated by Django 2.1.11 on 2019-08-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderTrack', '0002_auto_20190822_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='outcome',
        ),
        migrations.AddField(
            model_name='activity',
            name='outcome',
            field=models.CharField(choices=[('Outcome1', 'Outcome 1'), ('Outcome2', 'Outcome 2'), ('Outcome3', 'Outcome 3'), ('Outcome4', 'Outcome 4')], default='outcome 1', max_length=8),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sub_activity',
            field=models.CharField(max_length=500),
        ),
    ]
